# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jordanbeach', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['title']},
        ),
    ]
