# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jordanbeach', '0002_auto_20160715_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=400)),
                ('title', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=400)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('instructor', 'Instructor'), ('mentor', 'Mentor')], max_length=20)),
                ('year_start', models.PositiveSmallIntegerField()),
                ('year_end', models.PositiveSmallIntegerField(null=True)),
                ('course_name', models.CharField(max_length=200)),
                ('course_venue', models.CharField(max_length=200)),
                ('mentee', models.CharField(max_length=200, null=True)),
                ('mentee_role', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='pages',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal_issue',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal_vol',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
