# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jordanbeach', '0005_auto_20160724_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='venue',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
