# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jordanbeach', '0006_auto_20160724_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='pages',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
